service: product-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-west-1
  environment:
    SQS_URL:
      Ref: SQSQueue
    SNS_TOPIC:
      Ref: MyTopic  	
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - sqs:*
      Resource: '*'
    - Effect: "Allow"
      Action: 
        - sns:*
      Resource: '*'    
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "arn:aws:dynamodb:eu-west-1:*:table/*"
resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue 
      Properties:
        QueueName: catalogItemsQueue
    MyTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: Create Product Topic
        TopicName: createProductTopic
    MyEmailSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: email
        Endpoint: olga.novak.tests@gmail.com
        TopicArn:
          Ref: MyTopic                   
functions:
  products:
    handler: products.getProductsList
    environment:
      TABLE_NAME: HappyShopProduct
      TABLE_STORE: HappyShopStore
    events:
      - http:
          path: products
          method: get
          cors:
            origin: '*'
            headers:
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Methods
  product:
    handler: product.getProductsById
    environment:
      TABLE_NAME: HappyShopProduct
      TABLE_STORE: HappyShopStore
    events:
      - http:
          path: products/{productId}
          method: get
          cors:
            origin: '*'
            headers:
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Methods
            allowCredentials: false
  createProduct:
    handler: createProduct.createProduct
    environment:
      TABLE_NAME: HappyShopProduct
      TABLE_STORE: HappyShopStore
    events:
      - http:
          path: products
          method: put
          cors:
            origin: '*'
            headers:
              - Access-Control-Allow-Headers
              - Access-Control-Allow-Origin
              - Access-Control-Allow-Methods
            allowCredentials: false          
  catalogBatchProcess:
    environment:
      TABLE_NAME: HappyShopProduct
      TABLE_STORE: HappyShopStore
      SQS_URL:
        Ref: SQSQueue
      SNS_TOPIC:
        Ref: MyTopic  
    handler: catalogBatchProcess.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          enabled: true
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn
