service: autorization-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-west-1
plugins:
  - serverless-dotenv-plugin                   
functions:
  token:
    handler: token.token
    events:
      - http:
          method: get
          cors: true
          path: token
  basicAuthorizer:
    handler: basicAuthorizer.basicAuthorizer

