service: autorization-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-west-1
plugins:
  - serverless-dotenv-plugin                   
functions:
  token:
    handler: token.token
    events:
      - http:
          method: get
          cors: true
          path: token
          authorizer:
            name: tokenBasicAuthorizer
            type: token
            arn: arn:aws:lambda:eu-west-1:905418409104:function:autorization-service-dev-basicAuthorizer
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
  basicAuthorizer:
    handler: basicAuthorizer.basicAuthorizer

